---
title: Safe Conversion from Numeric to Integer
subtitle: Validating numbers before converting them to integers
author: Jeremy Selva [`r fontawesome::fa(name = "linkedin", fill = "#0077ac")`](https://www.linkedin.com/in/jeremy-selva-085b9112a/){target="_blank"} [`r fontawesome::fa(name = "github", fill = "#000000")`](https://github.com/JauntyJJS){target="_blank"} [`r fontawesome::fa(name = "fab fa-square-x-twitter", fill = "#000000")`](https://twitter.com/JauntyJJS){target="_blank"} [`r fontawesome::fa(name = "bluesky", fill = "#1084ff")`](https://bsky.app/profile/jauntyjjs.bsky.social){target="_blank"} [<svg aria-hidden="true" role="img" viewBox="0 0 512 512" style="height:1em;width:1em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:#5f53e7;overflow:visible;position:relative;"><path d="M433 179.1c0-97.2-63.7-125.7-63.7-125.7-62.5-28.7-228.6-28.4-290.5 0 0 0-63.7 28.5-63.7 125.7 0 115.7-6.6 259.4 105.6 289.1 40.5 10.7 75.3 13 103.3 11.4 50.8-2.8 79.3-18.1 79.3-18.1l-1.7-36.9s-36.3 11.4-77.1 10.1c-40.4-1.4-83-4.4-89.6-54a102.5 102.5 0 0 1 -.9-13.9c85.6 20.9 158.7 9.1 178.8 6.7 56.1-6.7 105-41.3 111.2-72.9 9.8-49.8 9-121.5 9-121.5zm-75.1 125.2h-46.6v-114.2c0-49.7-64-51.6-64 6.9v62.5h-46.3V197c0-58.5-64-56.6-64-6.9v114.2H90.2c0-122.1-5.2-147.9 18.4-175 25.9-28.9 79.8-30.8 103.8 6.1l11.6 19.5 11.6-19.5c24.1-37.1 78.1-34.8 103.8-6.1 23.7 27.3 18.4 53 18.4 175z"/></svg>](https://fosstodon.org/@JauntyJJS){target="_blank"} [`r fontawesome::fa(name = "link", fill = "#666666")`](https://jeremy-selva.netlify.app/){target="_blank"}
format: live-html
webr:
  packages:
    - tibble
    - dplyr
    - purrr
    - checkmate
    - reactable
    - pointblank
---

{{< include ../_extensions/r-wasm/live/_knitr.qmd >}}

```{webr}
#| include: false
#| envir: numeric to integer
#| label: set expression

# So that we can print pointblank results to the screen
options(expressions=10000)
```

:::{.goals}

::::{.goals-header}
Learning Goals
::::

::::{.goals-container}
  * Understand the need to check if numeric values can be converted to integers.
  * Use [`checkmate::testIntegerish`](https://mllg.github.io/checkmate/reference/checkIntegerish.html){target="_blank"} to check if an R object can be safely convertible to integer.
  * Use [`col_vals_exp`](https://rstudio.github.io/pointblank/reference/col_vals_expr.html){target="_blank"} to check if a column satisfy a custom-made condition/expression.
::::

:::

To save on memory space, sometimes you may wish to convert a `numeric` column to an `integer` column if it is safe to do so.

Consider this small data set `total_cacs_dataset` consisting of the patient's total coronary calcium Agatston score.

```{webr}
#| envir: numeric to integer
#| label: CACS numeric data set
#| echo: false
total_cacs_dataset <- tibble::tribble(
  ~`Patient ID` , ~`CACS Numeric Safe 1`, ~`CACS Numeric Safe 2`, ~`CACS Numeric Unsafe`,
    "Patient 1" ,                    746,                    746,                  746.9,   
    "Patient 2" ,                    853,                 853.00,                 853.00,     
    "Patient 3" ,                      0,                      0,                    0.5,                  
    "Patient 4" ,                     95,                     95,                   95.4,           
    "Patient 5" ,                     NA,                  343.0,                  343.0
)

reactable::reactable(
  total_cacs_dataset,
  defaultPageSize = 5
)

```

## Dangers of Unsafe Integer Conversion

If you take a look at the class (data type) of columns `CACS Numeric Safe 1`, `CACS Numeric Safe 2`, and `CACS Numeric Unsafe`, you will see that they are all set to `numeric`

```{webr}
#| envir: numeric to integer
#| label: class of CACS Numeric Safe 1
#| autorun: true
class(total_cacs_dataset[["CACS Numeric Safe 1"]])
```

```{webr}
#| envir: numeric to integer
#| label: class of CACS Numeric Safe 2
#| autorun: true
class(total_cacs_dataset[["CACS Numeric Safe 2"]])
```

```{webr}
#| envir: numeric to integer
#| label: class of CACS Numeric Safe 3
#| autorun: true
class(total_cacs_dataset[["CACS Numeric Unsafe"]])
```

We want to check in an automatic way if these column values can be safely be converted into type `integer` using the function `as.integer()` as doing this inaccurately can lead to a loss of precision. Observe that `746.9`, `0.5` and `95.9` are converted to `746`, `0` and `95`.

```{webr}
#| envir: numeric to integer
#| label: unsafe convertion
#| warning: true
as.integer(total_cacs_dataset[["CACS Numeric Unsafe"]])
```

## Check if a numeric column is safe for integer conversion

While [`pointblank`](https://rstudio.github.io/pointblank/index.html){target="_blank"} does not have a function that do that, we can create a customised validation that uses a predicate expression (a conditional R script of expression that returns a vector containing `TRUE`, `FALSE` or `NA`) and then use the function [`pointblank::col_vals_exp`](https://rstudio.github.io/pointblank/reference/col_vals_expr.html){target="_blank"} to identify which rows does not meet the predicate expression.

The predicate expression can be done using the function [`checkmate::testIntegerish`](https://mllg.github.io/checkmate/reference/checkIntegerish.html){target="_blank"} which returns `FALSE` if the input vector cannot be safely convertible to integer. To ensure that we have a `TRUE` or `FALSE` output for each element in the input vector, we use the function [`purrr::map_lgl`](https://purrr.tidyverse.org/reference/map.html){target="_blank"}. Here is an example using the column `CACS Numeric Unsafe` as an input to returns a vector containing `TRUE`, `FALSE` or `NA`.

```{webr}
#| envir: numeric to integer
#| label: identifying numeric values that cannot be safely converted to integer
#| autorun: false
total_cacs_dataset |> 
  dplyr::select(
    c("Patient ID" , "CACS Numeric Unsafe")
  ) |> 
  dplyr::mutate(
    safe_to_convert = purrr::map_lgl(
      .x = .data[["CACS Numeric Unsafe"]], 
      .f = checkmate::testIntegerish
    )
  )

```

We then use [`pointblank::col_vals_exp`](https://rstudio.github.io/pointblank/reference/col_vals_expr.html){target="_blank"} with the the predicate expression to isolate rows that cannot be safely convert to integer in the column `CACS Numeric Unsafe`.

```{webr}
#| envir: numeric to integer
#| label: identifying rows that cannot be safely converted to integer
#| autorun: true
total_cacs_dataset |> 
  pointblank::create_agent(
    tbl_name = "CACS Numeric Dataset",
    label = "CACS Numeric Dataset Vaidation"
  ) |> 
  pointblank::col_vals_expr(
    expr = pointblank::expr(
      purrr::map_lgl(
        .x = .data[["CACS Numeric Unsafe"]], 
        .f = checkmate::testIntegerish
      )
    )
  ) |> 
  pointblank::interrogate() |> 
  pointblank::get_sundered_data(
    type = "fail"
  )

```

Here is an example (using columns `CACS Numeric Safe 1` and `CACS Numeric Safe 2`) when the verification has no error allowing us to safely do the conversion.

```{webr}
#| envir: numeric to integer
#| label: safe conversion to integers after checking
#| autorun: false
total_cacs_dataset |> 
  pointblank::col_vals_expr(
    expr = pointblank::expr(
      purrr::map_lgl(
        .x = .data[["CACS Numeric Safe 1"]], 
        .f = checkmate::testIntegerish
      )
    )
  ) |> 
  pointblank::col_vals_expr(
    expr = pointblank::expr(
      purrr::map_lgl(
        .x = .data[["CACS Numeric Safe 2"]], 
        .f = checkmate::testIntegerish
      )
    )
  ) |> 
  dplyr::mutate(
    dplyr::across(
      .cols = c("CACS Numeric Safe 1", "CACS Numeric Safe 2"),
      .fns = as.integer
    )
  )

```

## What about `NA` values

If there is need to also catch rows with `NA` values, using the argument `na_pass = FALSE` in [`pointblank::col_vals_exp`](https://rstudio.github.io/pointblank/reference/col_vals_expr.html){target="_blank"} will not work.

This is because [`checkmate::testIntegerish`](https://mllg.github.io/checkmate/reference/checkIntegerish.html){target="_blank"} will return `TRUE` if the input is `NA`. Thus the predicate expression will never return an `NA` value.

```{webr}
#| envir: numeric to integer
#| label: testIntegerish on NA values
#| autorun: true
checkmate::testIntegerish(NA)
```

One way to overcome this is to add another validation using the function [`pointblank::col_vals_not_null`](https://rstudio.github.io/pointblank/reference/col_vals_not_null.html){target="_blank"}

```{webr}
#| envir: numeric to integer
#| label: safe conversion to integers and catch NA method 1
#| autorun: false
total_cacs_dataset |> 
  pointblank::create_agent(
    tbl_name = "CACS Numeric Dataset",
    label = "CACS Numeric Dataset Vaidation"
  ) |> 
  pointblank::col_vals_not_null(
    columns = colnames(total_cacs_dataset)
  ) |> 
  pointblank::col_vals_expr(
    expr = pointblank::expr(
      purrr::map_lgl(
        .x = .data[["CACS Numeric Safe 1"]], 
        .f = checkmate::testIntegerish
      )
    )
  ) |> 
  pointblank::col_vals_expr(
    expr = pointblank::expr(
      purrr::map_lgl(
        .x = .data[["CACS Numeric Safe 2"]], 
        .f = checkmate::testIntegerish
      )
    )
  ) |> 
  pointblank::col_vals_expr(
    expr = pointblank::expr(
      purrr::map_lgl(
        .x = .data[["CACS Numeric Unsafe"]], 
        .f = checkmate::testIntegerish
      )
    )
  ) |> 
  pointblank::interrogate()
```
