---
title: Validating Treatment Groupings
subtitle: Dealing with uniqueness, completeness and sets
author: Jeremy Selva [`r fontawesome::fa(name = "linkedin", fill = "#0077ac")`](https://www.linkedin.com/in/jeremy-selva-085b9112a/){target="_blank"} [`r fontawesome::fa(name = "github", fill = "#000000")`](https://github.com/JauntyJJS){target="_blank"} [`r fontawesome::fa(name = "fab fa-square-x-twitter", fill = "#000000")`](https://twitter.com/JauntyJJS){target="_blank"} [`r fontawesome::fa(name = "bluesky", fill = "#1084ff")`](https://bsky.app/profile/jauntyjjs.bsky.social){target="_blank"} [<svg aria-hidden="true" role="img" viewBox="0 0 512 512" style="height:1em;width:1em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:#5f53e7;overflow:visible;position:relative;"><path d="M433 179.1c0-97.2-63.7-125.7-63.7-125.7-62.5-28.7-228.6-28.4-290.5 0 0 0-63.7 28.5-63.7 125.7 0 115.7-6.6 259.4 105.6 289.1 40.5 10.7 75.3 13 103.3 11.4 50.8-2.8 79.3-18.1 79.3-18.1l-1.7-36.9s-36.3 11.4-77.1 10.1c-40.4-1.4-83-4.4-89.6-54a102.5 102.5 0 0 1 -.9-13.9c85.6 20.9 158.7 9.1 178.8 6.7 56.1-6.7 105-41.3 111.2-72.9 9.8-49.8 9-121.5 9-121.5zm-75.1 125.2h-46.6v-114.2c0-49.7-64-51.6-64 6.9v62.5h-46.3V197c0-58.5-64-56.6-64-6.9v114.2H90.2c0-122.1-5.2-147.9 18.4-175 25.9-28.9 79.8-30.8 103.8 6.1l11.6 19.5 11.6-19.5c24.1-37.1 78.1-34.8 103.8-6.1 23.7 27.3 18.4 53 18.4 175z"/></svg>](https://fosstodon.org/@JauntyJJS){target="_blank"} [`r fontawesome::fa(name = "link", fill = "#666666")`](https://jeremy-selva.netlify.app/){target="_blank"}
format: live-html
webr:
  packages:
    - tibble
    - reactable
    - pointblank
---

{{< include ../_extensions/r-wasm/live/_knitr.qmd >}}

```{webr}
#| include: false
#| envir: treatment group
#| label: set expression

# So that we can print pointblank results to the screen
options(expressions=10000)
```

:::{.goals}

::::{.goals-header}
Learning Goals
::::

::::{.goals-container}
  * Check if the provided columns have unique row values using [`rows_distinct`](https://rstudio.github.io/pointblank/reference/rows_distinct.html){target="_blank"}.
  * Check if the provided columns do not have `NA` values using [`col_vals_not_null`](https://rstudio.github.io/pointblank/reference/col_vals_not_null.html){target="_blank"}.
  * Check if the provided columns contain specific values from a given set using [`col_vals_in_set`](https://rstudio.github.io/pointblank/reference/col_vals_in_set.html){target="_blank"}.
::::

:::

Consider this small data set `treatment_group_dataset` consisting of the patient's treatment group in a clinical trial to understand the treatment effects of a pharmaceutical compound.

```{webr}
#| envir: treatment group
#| label: small treatment group data set
#| echo: false

treatment_group_dataset <- tibble::tribble(
  ~`Patient ID` , ~`Balanced Grouping`, ~`Invalid Grouping`,
    "Patient 1" ,          "Placebo"  ,        "Treatment" ,        
    "Patient 2" ,          "Placebo"  ,        "Placebo"   ,         
    "Patient 3" ,          "Placebo"  ,        "Treatment" ,              
    "Patient 4" ,          "Treatment",        "Placebo"   ,           
    "Patient 5" ,          "Placebo"  ,        "Placebo"   ,            
    "Patient 6" ,          "Treatment",        "Placebo"   ,
    "Patient 7" ,          "Placebo"  ,        "Plaecbo"   ,           
    "Patient 8" ,          "Placebo"  ,        "Placebo"   ,         
    "Patient 9" ,          "Treatment",        "Treatment" ,              
    "Patient 10",          "Treatment",        "Treatment" ,     
    "Patient 11",          "Treatment",        "Treatment" ,       
    "Patient 12",          "Placebo"  ,        "Placebo"   , 
    "Patient 13",          "Treatment",        "Treatment" ,           
    "Patient 14",          "Treatment",        "Treatment" ,           
    "Patient 15",          "Treatment",        "Treatmment", 
    "Patient 16",          "Placebo"  ,        "Placebo"   ,           
    "Patient 17",          "Placebo"  ,        "Placebo"   , 
    "Patient 18",          "Placebo"  ,        "Placebo"   , 
    "Patient 19",          "Treatment",        "NA"        , 
    "Patient 20",          "Treatment",        NA
)

reactable::reactable(
  treatment_group_dataset,
  defaultPageSize = 5
)

```

## Check if patient ID is unique and complete

We verify if the values in the column `Patient ID` are unique and have no missing values using [`rows_distinct`](https://rstudio.github.io/pointblank/reference/rows_distinct.html){target="_blank"} and [`pointblank::col_vals_not_null`](https://rstudio.github.io/pointblank/reference/col_vals_not_null.html){target="_blank"} respectively.

```{webr}
#| envir: treatment group
#| label: unique patient ID
#| autorun: false
treatment_group_dataset |> 
  pointblank::rows_distinct(
    columns = c("Patient ID")
  ) |> 
  pointblank::col_vals_not_null(
    columns = c("Patient ID")
  )

```

## Check if all patients are given a treatment group

In this data set, a patient can only be assigned to either the `Placebo` or `Treatment` group. To verify this, we use the function [`col_vals_in_set`](https://rstudio.github.io/pointblank/reference/col_vals_in_set.html){target="_blank"}. A new parameter to take note is `set` which we need to specify the relevant groups the column needs to have. This is done by setting `set = c("Placebo", "Treatment")`.

Here is an example (using columns `Balanced Grouping` and `Imbalanced Grouping`) when the verification has no error.

```{webr}
#| envir: treatment group
#| label: checking column Balanced Grouping for valid groups
#| autorun: false
treatment_group_dataset |> 
  pointblank::col_vals_in_set(
    columns = c("Balanced Grouping"),
    set = c("Placebo", "Treatment")
  )

```

The column `Invalid Grouping` has patients which do not pass the validation.

```{webr}
#| envir: treatment group
#| label: checking column Invalid Grouping for valid groups
#| autorun: true
treatment_group_dataset |> 
  pointblank::col_vals_in_set(
    columns = c("Invalid Grouping"),
    set = c("Placebo", "Treatment")
  )

```

We can use [`create_agent()`](https://rstudio.github.io/pointblank/reference/create_agent.html){target="_blank"}, [`interrogate()`](https://rstudio.github.io/pointblank/reference/interrogate.html){target="_blank"} and [`get_sundered_data()`](https://rstudio.github.io/pointblank/reference/get_sundered_data.html){target="_blank"} to obtain patients with issues.

```{webr}
#| envir: treatment group
#| label: identifying rows that gives column Invalid Grouping issues
#| autorun: false
treatment_group_dataset |> 
  pointblank::create_agent(
    tbl_name = "Treatment Group Dataset",
    label = "Treatment Group Dataset Vaidation"
  ) |> 
  pointblank::col_vals_in_set(
    columns = c("Invalid Grouping"),
    set = c("Placebo", "Treatment")
  ) |> 
  pointblank::interrogate() |> 
  pointblank::get_sundered_data(
    type = "fail"
  )

```

We can see that the patients that do not meet the criteria have either missing data or spelling mistakes.

