project:
  type: website
  output-dir: docs
  
execute:
  freeze: false

website:
  title: "Clinical Data Validation in R"
  description: A guide on how to do clinical data validation using some R packages.
  page-navigation: true
  sidebar:
    logo: "images/image.jpg"
    background: "#F5F5F5"
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        # text: Welcome
      - section: "Validation Basics"
        contents:
          - getting_started/introduction.qmd
          - getting_started/treatment_control.qmd
          - getting_started/bmi.qmd
          - getting_started/convert_numeric_to_integer.qmd
      - section: "R Programming"  
        contents:
          - r_intro/r_code.qmd

format:
  live-html:
    grid:
      sidebar-width: 270px
      margin-width: 250px
    backgroundcolor: "#FFFFFF"



