project:
  type: website
  output-dir: docs

engine: knitr
  
execute:
  freeze: false

website:
  title: "Clinical Data Validation in R"
  description: A guide on how to do clinical data validation using some R packages.
  page-navigation: true
  sidebar:
    logo: "images/image.jpg"
    background: "#F5F5F5"
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        # text: Welcome
      - section: "Validation Basics"
        contents:
          - validation_basic/introduction.qmd
          - validation_basic/treatment_control.qmd
          - validation_basic/bmi.qmd
      - section: "Validation Advanced"
        contents:
          - validation_advanced/convert_numeric_to_integer.qmd
      - section: "R Programming"  
        contents:
          - r_intro/r_code.qmd
          - r_intro/data_wrangling.qmd

format:
  live-html:
    toc: true
    theme:
      - customstyle.scss
    grid:
      sidebar-width: 270px
      margin-width: 250px
    backgroundcolor: "#FFFFFF"
    # css: 
    #   - _style.css
    #   - _webex.css
    # include-after-body: 
    #   - _webex.js
    #   - _displayall.js


