---
title: "Basic Data Wrangling"
author: Jeremy Selva [`r fontawesome::fa(name = "linkedin", fill = "#0077ac")`](https://www.linkedin.com/in/jeremy-selva-085b9112a/){target="_blank"} [`r fontawesome::fa(name = "github", fill = "#000000")`](https://github.com/JauntyJJS){target="_blank"} [`r fontawesome::fa(name = "fab fa-square-x-twitter", fill = "#000000")`](https://twitter.com/JauntyJJS){target="_blank"} [`r fontawesome::fa(name = "bluesky", fill = "#1084ff")`](https://bsky.app/profile/jauntyjjs.bsky.social){target="_blank"} [<svg aria-hidden="true" role="img" viewBox="0 0 512 512" style="height:1em;width:1em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:#5f53e7;overflow:visible;position:relative;"><path d="M433 179.1c0-97.2-63.7-125.7-63.7-125.7-62.5-28.7-228.6-28.4-290.5 0 0 0-63.7 28.5-63.7 125.7 0 115.7-6.6 259.4 105.6 289.1 40.5 10.7 75.3 13 103.3 11.4 50.8-2.8 79.3-18.1 79.3-18.1l-1.7-36.9s-36.3 11.4-77.1 10.1c-40.4-1.4-83-4.4-89.6-54a102.5 102.5 0 0 1 -.9-13.9c85.6 20.9 158.7 9.1 178.8 6.7 56.1-6.7 105-41.3 111.2-72.9 9.8-49.8 9-121.5 9-121.5zm-75.1 125.2h-46.6v-114.2c0-49.7-64-51.6-64 6.9v62.5h-46.3V197c0-58.5-64-56.6-64-6.9v114.2H90.2c0-122.1-5.2-147.9 18.4-175 25.9-28.9 79.8-30.8 103.8 6.1l11.6 19.5 11.6-19.5c24.1-37.1 78.1-34.8 103.8-6.1 23.7 27.3 18.4 53 18.4 175z"/></svg>](https://fosstodon.org/@JauntyJJS){target="_blank"} [`r fontawesome::fa(name = "link", fill = "#666666")`](https://jeremy-selva.netlify.app/){target="_blank"}
format: live-html
webr:
  packages:
    - medicaldata
    - dplyr
---

{{< include ../_extensions/r-wasm/live/_knitr.qmd >}}

In this session, we will go through the basic of data wrangling using the [Obstetrics and Periodontal Therapy study dataset](https://higgi13425.github.io/medicaldata/reference/opt.html){target="_blank"} from the R package [`medicaldata`](https://higgi13425.github.io/medicaldata/){target="_blank"}.

:::{.goals}

::::{.goals-header}
Learning Goals
::::

::::{.goals-container}
  * Identify the overall data structure. 
  * Using R to view the data by subsetting.
  * Introducing the R native pipe operator `|>`.
  * Using R package [`dplyr`](https://dplyr.tidyverse.org/){target="_blank"} to perfrom simple data wrangling.
::::

:::

The Obstetrics and Periodontal Therapy study was a multi-center randomized controlled trial to determine if nonsurgical periodontal treatment intervention can reduce the risk of preterm birth (< 37 weeks) and low birth weight (< 2500 g) outcomes. 

823 participants enrolled at 4 centers underwent stratified randomization, resulting in 413 women assigned to the treatment group and 410 to control. Treatment group consist of women treated before 21 weeks gestation (treatment) while the control consist of women treated after delivery (control). All participants were 13-16 weeks pregnant at time of randomization (baseline/visit 1).

## Overall data structure

The data can be accessed from `medicaldata::opt`. However, we can see that using the `print` function alone has its limitations when the data has a large number of rows and columns.

::: {.scrollable-output}

```{webr}
#| caption: Using the print function
#| label: Viewing opt data using print
print(medicaldata::opt)
```

:::

<br>

We can start by identifying how many rows and columns `medicaldata::opt` has. This can be done using `nrow()` and `ncol()` respectively. The `dim()` function prints the numbers of rows and columns simultaneously.

::: {.panel-tabset}

### 
Click on the different tabs.

### nrow

```{webr}
#| caption: Using the nrow function
#| label: Viewing number of rows in opt
nrow(medicaldata::opt)
```

### ncol

```{webr}
#| caption: Using the ncol function
#| label: Viewing number of columns in opt
ncol(medicaldata::opt)
```

### dim

```{webr}
#| caption: Using the dim function
#| label: Viewing number of rows and columns in opt
dim(medicaldata::opt)
```

:::

Next, we can also try to identify the column names using `colnames`. Details of each column name can be found in [here](https://higgi13425.github.io/medicaldata/reference/opt.html){target="_blank"}.

::: {.scrollable-output}

```{webr}
#| caption: Using the colnames function
#| label: Viewing column names in opt
colnames(medicaldata::opt)
```

:::

<br>

## Subsetting the data

Sometimes we just want to take a peak on specific areas of the dataset instead of printing everything on the screen. Here are some additional functions that can be useful.

::: {.panel-tabset}

### 
Click on the different tabs.

### head

The `head()` function can be used to view the first `n` rows of a dataset, where users can choose `n` any value greater than 0. By default, n is 6.

::: {.scrollable-output}

```{webr}
#| caption: Using the head function
#| label: Viewing the first few number of rows in opt
head(medicaldata::opt)
```

:::

::: {.scrollable-output}

```{webr}
#| caption: Using the head function to see the first 2 rows
#| label: Viewing the first 2 rows in opt
head(medicaldata::opt, n = 2)
```

:::

### tail

The `tail()` function can be used to view the last `n` rows of a dataset, where users can choose `n` any value greater than 0. By default, n is 6.

::: {.scrollable-output}

```{webr}
#| caption: Using the tail function
#| label: Viewing the last few number of rows in opt
tail(medicaldata::opt)
```

:::

::: {.scrollable-output}

```{webr}
#| caption: Using the tail function to see the last 2 rows
#| label: Viewing the last 2 rows in opt
tail(medicaldata::opt, n = 2)
```

:::

### $

The `$` can be used to access one column in a data frame. It uses the syntax.

```r
dataframe$column_name
```
Observe that the output is a vector.

```{webr}
#| caption: Using the $ operator to see the Age column as a vector
#| label: accessing the first 10 rows of the Age columns as a vector
head(medicaldata::opt$Age, n = 10)
class(head(medicaldata::opt$Age, n = 10))
```

### []

You can select elements from a data frame with the help of square brackets `[]`.

In this example, we pick the first column.

```{webr}
#| caption: Using the [] operator to see the first column as a data frame
#| label: using the [] operator to see the first column as a data frame
head(medicaldata::opt[1], n = 5)
class(head(medicaldata::opt[1], n = 5))
```

In this example, we pick the `Age` column.

```{webr}
#| caption: Using the [] operator to see the Age column as a data frame
#| label: using the [] operator to see the Age column as a data frame
head(medicaldata::opt[c("Age")])
class(head(medicaldata::opt[c("Age")], n = 5))
```

Multiple columns can also be selected as well.

In this example, we pick the first, as well as the fifth to ninth column.

```{webr}
#| caption: Using the [] operator to select multiple columns using column index
#| label: using the [] operator to select multiple columns using column index
head(medicaldata::opt[c(1,5:9)], n = 5)
```

In this example, we pick the columns `PID`, `Group` and `Age`.

```{webr}
#| caption: Using the [] operator to select multiple columns using column names
#| label: using the [] operator to select multiple columns using column names
head(medicaldata::opt[c("PID", "Group", "Age")], n = 5)
```

### [,]

By using a comma, you can indicate what to select from the rows and the columns respectively.

In this example, we pick rows 3, 5 to 10 and columns 1, 4 to 9.

```{webr}
#| caption: specific columns and rows using numbers
#| label: specific columns and rows using numbers
medicaldata::opt[c(3,5:9), c(1,4:9)]
```

Column names can also be used

```{webr}
#| caption: specific columns and rows using numbers and column names
#| label: specific columns and rows using numbers and column names
columns_I_want <- c("PID", "Group", "Age", "Black", "White", "Nat.Am", "Asian", "Hisp")
medicaldata::opt[c(3,5:9), columns_I_want]
```

If columns are not specified, it means selects all columns.

::: {.scrollable-output}

```{webr}
#| caption: selects all columns
#| label: selects all columns
medicaldata::opt[c(3,5:9), ]
```

:::

The same applies for rows.

::: {.scrollable-output}

```{webr}
#| caption: selects all row
#| label: selects all row.
medicaldata::opt[ ,c(1,4:9)]
```

:::

### [,]

:::

## The `|>` operator

Earlier we have run the following code:

```r
class(head(medicaldata::opt[1], n = 5))
```

This line of code involves applying two functions to `medicaldata::opt[1]`.

In reality, a data analysis pipeline may involve a serial chain of multiple functions.

This may give rises to deeply nested parentheses (have to read from right to left) like

```r
processed_data <- task_3(task_2(task_1(data)))
```

or numerous temporary variables (have to read in a z-shaped manner)

```r
data_after_task_1 <- task_1(data)
data_after_task_2 <- task_2(data_after_task_1)
processed_data <- task_3(data_after_task_2)
```
which can be hard to read and debug, especially when it gives an error on a new dataset.

To increase code readability and inspired by the [pipe operator `|` in Linux](https://www.geeksforgeeks.org/linux-unix/piping-in-unix-or-linux/){target="_blank"}, R 4.1.0 introduced a native pipe operator `|>` such that the above code can be rewritten as a form that can be read from left to right

```r
processed_data <- data |> task_1() |> task_2() |> task_3()
```

or top to bottom like a pipeline.

```r
processed_data <- data |> 
  task_1() |> 
  task_2() |> 
  task_3()
```

Coming back to

```r
class(head(medicaldata::opt[1], n = 5))
```

it can be rewritten as the follows:

```{webr}
#| caption: R native pipe example
#| label: R native pipe example
medicaldata::opt[1] |> 
  head(n = 5) |> 
  class()
```

## Using `dplyr`

Data wrangling involves transforming the data into a format that is more appropriate and valuable for further downstream analysis. This process may involve creating new columns, choosing specific rows or columns that satisfy a specific condition.

The R package [`dplyr`](https://dplyr.tidyverse.org/){target="_blank"} provides some functions that makes this process easier. Below are some of the commonly used functions.

::: {.panel-tabset}

### 
Click on the different tabs.

### dplyr::select

[`dplyr::select`](https://dplyr.tidyverse.org/reference/select.html){target="_blank"} is used to choose columns based on a condition.

```{webr}
#| caption: select column names
#| label: select column names
medicaldata::opt |> 
  dplyr::select(c("PID", "Group", "Age")) |> 
  head(n = 5)
```

If an external vector needs to used, you can use [`dplyr::all_of`](https://tidyselect.r-lib.org/reference/all_of.html){target="_blank"} or [`dplyr::any_of`](https://tidyselect.r-lib.org/reference/all_of.html){target="_blank"}

```{webr}
#| caption: select column names using external vector
#| label: select column names using external vector
columns_I_want <- c("PID", "Group", "Age", "Black", "White", "Nat.Am", "Asian", "Hisp")
medicaldata::opt |> 
  dplyr::select(dplyr::all_of(columns_I_want)) |> 
  head(n = 5)
```

This is useful if we need to ensure that certain columns exists when the dataset has been updated to a new version.

```{webr}
#| caption: select column names with invalid names using all_of
#| label: select column names with invalid names using all_of
#| error: true
columns_I_want <- c("PID", "Group", "Ages", "Hisps")
medicaldata::opt |> 
  dplyr::select(dplyr::all_of(columns_I_want)) |> 
  head(n = 5)
```

```{webr}
#| caption: select column names with invalid names using any_of
#| label: select column names with invalid names using any_of
columns_I_want <- c("PID", "Group", "Ages", "Hisps")
medicaldata::opt |> 
  dplyr::select(dplyr::any_of(columns_I_want)) |> 
  head(n = 5)
```

The [documentation](https://dplyr.tidyverse.org/reference/select.html){target="_blank"} indicates many helper function that you can use that can hep you pick very specific columns.

Below is an example using [`dplyr::starts_with`](https://tidyselect.r-lib.org/reference/starts_with.html){target="_blank"} and [`dplyr::ends_with`](https://tidyselect.r-lib.org/reference/starts_with.html){target="_blank"}.

```{webr}
#| caption: select column names that starts with BL
#| label: select column names that starts with BL
#| error: true
medicaldata::opt |> 
  dplyr::select(
    c("PID"),
    dplyr::starts_with("BL") & dplyr::ends_with("PG")
  ) |> 
  head(n = 5)
```

### dplyr::filter

[`dplyr::filter`](https://dplyr.tidyverse.org/reference/filter.html){target="_blank"} is used to choose rows based on a condition. Please note that [`dplyr::filter`](https://dplyr.tidyverse.org/reference/filter.html){target="_blank"} treats `NA` as FALSE and drops them.

To choose a column in the dataset using the pipe `|>` operator, we can use the syntax `.data[[{column_name}]]` to subset a column from a data frame using a character string or column_name as a variable is stored as a string like `column_name <- "Hisp"`

Below is an example to pick participants who are Hispanic or has a value of `Yes` in the `Hisp` column.

```{webr}
#| caption: filter by Hispanic
#| label: filter by Hispanic
medicaldata::opt |> 
  dplyr::select(
    dplyr::all_of(c("PID", "Hisp"))
  ) |> 
  dplyr::filter(
    .data[["Hisp"]] == "Yes"
  )|> 
  head(n = 5)
```

Here is an example with the use of comparison operators to keep participants between 20 and 60 who have a non-missing value in the `BMI` column.

```{webr}
#| caption: filter by age and bmi
#| label: filter by age and bmi
medicaldata::opt |> 
  dplyr::select(
    c("PID", "Age", "BMI")
  ) |> 
  dplyr::filter(
    .data[["Age"]] >= 20 & 
    .data[["Age"]] <= 60 &
    !is.na(.data[["BMI"]])
  ) |> 
  head(n = 10)
```

### dplyr::filter_out

[`dplyr::filter_out`](https://dplyr.tidyverse.org/reference/filter.html){target="_blank"} is used to drop rows based on a condition. Please note that [`dplyr::filter_out`](https://dplyr.tidyverse.org/reference/filter.html){target="_blank"} treats `NA` as FALSE but keeps them.

We can take a look at the difference using the column `BMI` which has missing values to see its usefulness.

Suppose we want to only remove participants with BMI above 25, if we use [`dplyr::filter`](https://dplyr.tidyverse.org/reference/filter.html){target="_blank"} like below.

::: {.scrollable-output}

```{webr}
#| caption: filter bmi over 25 wrongly
#| label: filter bmi over 25 wrongly
medicaldata::opt |> 
  dplyr::select(c("PID", "Age", "BMI")) |> 
  dplyr::filter(
    .data[["BMI"]] <= 25
  )
```

:::

We most likely forget to take those with missing BMI into consideration and remove them by mistake... until someone else tells you that the number remaining should be `r nrow(medicaldata::opt) - sum(medicaldata::opt$BMI > 25, na.rm = TRUE)` using the R code

```r
nrow(medicaldata::opt) - sum(medicaldata::opt$BMI > 25, na.rm = TRUE)
```

One workaround is add an additional condition to keep participants with missing BMI.

::: {.scrollable-output}

```{webr}
#| caption: filter bmi over 25 correctly with filter
#| label: filter bmi over 25 correctly with filter
medicaldata::opt |> 
  dplyr::select(c("PID", "Age", "BMI")) |> 
  dplyr::filter(
    .data[["BMI"]] <= 25 | is.na(.data[["BMI"]])
  )
```

:::

<br>

But with [`dplyr::filter_out`](https://dplyr.tidyverse.org/reference/filter.html){target="_blank"}, things are much more clearer.

::: {.scrollable-output}

```{webr}
#| caption: filter bmi over 25 correctly using filter_out
#| label: filter bmi over 25 correctly using filter_out
medicaldata::opt |> 
  dplyr::select(c("PID", "Age", "BMI")) |> 
  dplyr::filter_out(
    .data[["BMI"]] > 25
  )
```

:::

<br>

### dplyr::case_when

[`dplyr::case_when`](https://dplyr.tidyverse.org/reference/case-and-replace-when.html){target="_blank"} allows one for a given vector to check for multiple conditions and assign different values for each case. Below is the common use syntax.

```r
dplyr::case_when(
  condition_1 ~ result_1,    # Give result_1 if condition_1 is TRUE
  condition_2 ~ result_2,    # Give result_2 if condition_2 is TRUE & condition_1 is FALSE
  condition_3 ~ result_3,    # Give result_3 if condition_3 is TRUE & both condition_1 and condition_2 are FALSE
  .default = default_result  # Give default_result if none of the conditions above are TRUE
)
```
Let us look at the first ten BMI data as an example.

```{webr}
#| caption: create bmi data
#| label: create bmi data
#| envir: create bmi data for case when
#| autorun: true
bmi_data <- data.frame(
  id = medicaldata::opt$PID[1:10],
  bmi = medicaldata::opt$BMI[1:10]
)

bmi_data
```


::: {.scrollable-output}

```{webr}
#| caption: grouping bmi using case_when
#| label: grouping bmi using case_when
#| envir: create bmi data for case when
dplyr::case_when(
  is.na(bmi_data[["bmi"]]) ~ "Missing",
  bmi_data[["bmi"]] <= 20 ~ "20 and below",
  bmi_data[["bmi"]] >= 21 &  bmi_data[["bmi"]] <= 25 ~ "21 to 25",
  .default = "Not allocated Yet"
)
```

<br>

:::

### dplyr::mutate

[`dplyr::mutate`](https://dplyr.tidyverse.org/reference/mutate.html){target="_blank"} can be used to add new columns or update existing ones.

The below example shows new columns `age_in_ten_years` and `bmi_group` are created.

```{webr}
#| caption: create bmi and age data
#| label: create bmi and age data
#| envir: create bmi and age data for mutate
#| autorun: true
bmi_age_data <- data.frame(
  id = medicaldata::opt$PID[1:10],
  age = medicaldata::opt$Age[1:10],
  bmi = medicaldata::opt$BMI[1:10]
)

bmi_age_data
```

::: {.scrollable-output}

```{webr}
#| caption: create new columns using mutate
#| label: create new columns using mutate
#| envir: create bmi and age data for mutate
bmi_age_data <- bmi_age_data |> 
  dplyr::mutate(
    age_in_ten_years = .data[["age"]] + 10,
    bmi_group = dplyr::case_when(
      is.na(.data[["bmi"]]) ~ "Missing",
      .data[["bmi"]] <= 20 ~ "20 and below",
      .data[["bmi"]] >= 21 &  .data[["bmi"]] <= 25 ~ "21 to 25",
      .default = "Not allocated Yet"
    )
  )  

bmi_age_data
```

<br>

:::

:::
