---
title: "Getting Started"
author: "Jeremy Selva"
format: live-html
---

{{< include ../_extensions/r-wasm/live/_knitr.qmd >}}

## Introduction to R

R is a programming language that was initially designed for statistical analysis. It later got popular among data scientists. In practice, most data science teams use a mix of programming languages, often at least R and Python. Nevertheless, it is better to master one tool at a time and R is a great place to start. Keep in mind that R is not just software. There are many wonderful open communities with contributors all working to make R easier to learn and more enjoyable to use.

Like learning a new language (spoken or computer), the initial learning curve may be steep. We hope that this section can help you climb the initial learning curve and provide you with the basic skills and self-confidence to further your experience in using R.

:::{.goals}

::::{.goals-header}
Learning Goals
::::

::::{.goals-container}
  * Use functions from R.
  * Understand objects from R.
  * Know the different data types in R.
  * Perform comparisons in R
::::

:::

### Functions

Let's take a look on this first line of code. Click on the button `Run Code` to see the output.

```{webr}
#| caption: Using the print function
#| label: print function
print("Hello R 😃")
```

You will see that `Hello R 😃` is printed to the screen.

In this example, `print()` is a **function**, and its job is to print whatever text we place in between the double quotes `"`. Try putting a different text in this exercise below.

```{webr}
#| caption: Exercise using print
#| exercise: exercise_print
print("_Your_text_here_")
```

::: { .solution exercise="exercise_print" }
::: { .callout-tip collapse="false"}
#### Fully worked solution:

```r
print("Well done ! 👏")
```

:::
:::


**Function** names are usually action words represented with an open and close parentheses `()` in the following form.

```r
bake(cake)
```

In the above example, `bake()` is the function and the input `cake` is formally called an **argument** of the function.

It is possible for a function to accept more than one arguments or no arguments at all.

```r
bake(cake, banana, chocolate)
bake()
```

Here is an example of a function `Sys.time()` which does not need an argument. It gives the current date, time and time zones value.

```{webr}
#| label: print date time
Sys.time()
```

### Objects

Most things in R are an object. An R object can be almost anything, from a single number, symbol or character string (like a word) to a highly complex structure like a plot or dataset. We can create an object and assign values to the created object. A created object is sometimes called a variable.

Consider the line of code below,

```r
number_of_patients_in_ward_A <- 20
```

In this example, both `<-` and `20` are **objects** that R provides. The **variable** `number_of_patients_in_ward_A` is the object created. We assign the value `20` to `number_of_patients_in_ward_A` using the symbol `<-`. In R, the symbol `<-` is called an **object assignment operator**. It comprised of a "less than" symbol `<` and a hyphen `-`.

As a result, `number_of_patients_in_ward_A` holds the value of `20`, which R then stored it into memory.

```{webr}
#| envir: r_as_calculator_example
#| label: object assignement
#| autorun: true
number_of_patients_in_ward_A <- 20
number_of_patients_in_ward_A
```

Since `number_of_patients_in_ward_A` is stored in memory as a number, we can perform different operations such as adding and removing patients.

```{webr}
#| envir: r_as_calculator_example
#| label: patient calculation
number_of_patients_in_ward_A + 10
number_of_patients_in_ward_A - 10
number_of_patients_in_ward_A * 10
number_of_patients_in_ward_A / 10
```

## Data Types

### Atomic Classes

We share a few common atomic classes in R.

   - logical (`TRUE`, `FALSE`)
   - numeric (real or decimal) (`2`, `2.0`, `pi`)
   - integer (`2L`, `as.integer(3)`)
   - character (`"a"`, `"swc"`)

They can be identified using the function `class()`. Below are some examples that you can try it out.

```{webr}
#| label: logical atomic classes
i_am_true <- TRUE
i_am_false <- FALSE
i_am_not_applicable <- NA
class(i_am_true)
class(i_am_false)
class(i_am_not_applicable)
```

```{webr}
#| label: numeric atomic classes
i_am_numeric <- 2.00
i_am_pi <- pi
class(i_am_numeric)
```

To assign an explicit integer, we add an `L` beside the number.

```{webr}
#| label: integer atomic classes
i_am_integer <- 2L
class(i_am_integer)
```

```{webr}
#| label: character atomic classes
encouragement <- "You can do this 🌈🌻✨😊❤"
class(encouragement)
```

### Data Structure

R also has several common data structures.

   - vector
   - factors (1st, 2nd, 3rd, ...)
   - data frame

A vector is an one-dimensional data structure of the same atomic class (logical, numeric, character, ...).
To create a vector in R, we use the function `c()` works by combining objects together. Below are some examples done to create `ward_names` as a character vector and `number_of_patients` as a numeric vector. 

```{webr}
#| envir: making_datas
#| label: hospital_vector_example 
ward_names <- c("Ward A", "Ward B", "Ward C", "Ward D")
number_of_patients <- c(10, 17, 12, 4)

ward_names
number_of_patients
```

We can check if a given variable is a vector using the function `is.vector`. In addition, `class()` can be used to identify which atomic class the vector contains.

```{webr}
#| envir: making_datas
#| label: ward_names_check
is.vector(ward_names)
class(ward_names)
```

```{webr}
#| envir: making_datas
#| label: number_of_patients_check
is.vector(number_of_patients)
class(number_of_patients)
```

Factors are special kind of vectors that represent categorical data. They can be created using the `factor()` function. The most common input is a character vector. It also has a parameter called `levels` that accepts an optional vector of the unique values that tells R if the category has an order to follow.

```{webr}
#| envir: making_datas
#| label: hospital_factor_example 
ward_capacity <- factor(
  c("medium", "high", "medium", "low"),
  levels = c("low", "medium", "high")
)

ward_capacity
```

We can check if a given variable is a factor using the function `is.factor()` or `class()`.

```{webr}
#| envir: making_datas
#| label: ward_capacity_check
is.factor(ward_capacity)
class(ward_capacity)
```

We can build **data frame** from the **vectors** created earlier using the function, `data.frame()`.

```{webr}
#| envir: making_datas
#| label: hosptial_data
hospital <- data.frame(
  wards = ward_names,
  patient_count = number_of_patients,
  capacity = ward_capacity
)

hospital
```

We can check if a given variable is a data frame using the function `is.data.frame()`. `str()` helps to provide the atomic class information for each column in the data frame.

```{webr}
#| envir: making_datas
#| label: data_frame_check
is.data.frame(hospital)
str(hospital)
```

## Operators

Consider the number of patients in different wards.

```{webr}
#| envir: making_comparisons
#| label: patient in different wards
#| autorun: true
patient_count_in_ward_A <- 10
patient_count_in_ward_B <- 5
patient_count_in_ward_C <- 12
patient_count_in_ward_D <- 10
patient_count_in_ward_E <- 20

```

### Comparison Operators

R has operators (`>`, `>=`, `<`, `<=`, `==`, `!=`) to compare the relationship between two values. They usually returns `TRUE` or `FALSE`. 

::: {.panel-tabset}

#### >

The `>` operator means greater than.

```{webr}
#| envir: making_comparisons
#| label: greater than
patient_count_in_ward_A > patient_count_in_ward_B
patient_count_in_ward_A > patient_count_in_ward_C
patient_count_in_ward_A > patient_count_in_ward_D
```

#### >=

The `>=` operator means greater than or equal to.

```{webr}
#| envir: making_comparisons
#| label: greater than or equal to
patient_count_in_ward_A > patient_count_in_ward_B
patient_count_in_ward_A > patient_count_in_ward_C
patient_count_in_ward_A > patient_count_in_ward_D
```

#### <

The `<` operator means less than.

```{webr}
#| envir: making_comparisons
#| label: less than
patient_count_in_ward_A < patient_count_in_ward_B
patient_count_in_ward_A < patient_count_in_ward_C
patient_count_in_ward_A < patient_count_in_ward_D
```

#### <=

The `<=` operator means less than or equal to.

```{webr}
#| envir: making_comparisons
#| label: less than or equal to
patient_count_in_ward_A <= patient_count_in_ward_B
patient_count_in_ward_A <= patient_count_in_ward_C
patient_count_in_ward_A <= patient_count_in_ward_D
```

#### ==

The `==` operator means equal to.

```{webr}
#| envir: making_comparisons
#| label: equal to
patient_count_in_ward_A == patient_count_in_ward_B
patient_count_in_ward_A == patient_count_in_ward_C
patient_count_in_ward_A == patient_count_in_ward_D
```

#### !=

The `!=` operator means not equal to.

```{webr}
#| envir: making_comparisons
#| label: not equal to
patient_count_in_ward_A != patient_count_in_ward_B
patient_count_in_ward_A != patient_count_in_ward_C
patient_count_in_ward_A != patient_count_in_ward_D
```

:::

These comparison operators can be used to compare each element in a vector individually.

```{webr}
#| envir: making_comparisons
#| label: max capacity
#| autorun: true
wards <- c(
  patient_count_in_ward_A,
  patient_count_in_ward_B,
  patient_count_in_ward_C,
  patient_count_in_ward_D,
  patient_count_in_ward_E
)

max_capacity <- 12
desired_capacity_each_ward <- c(10, 5, 10, 5, 10)
```

```{webr}
#| envir: making_comparisons
#| label: vector comparison one
wards <= max_capacity
wards <= desired_capacity_each_ward

```

### Logical Operators

R has logical operators (`&`, `|`, `!`, `is.na()`, `isTRUE()`, `isFALSE()`, `%in%`, `%notin%`) to compare multiple operation. They usually returns `TRUE` or `FALSE`.

::: {.panel-tabset}

#### &

The `&` operator means logical AND which returns `TRUE` if both conditions are true.

```{webr}
#| envir: making_comparisons
#| label: logical AND
# TRUE & TRUE case
(patient_count_in_ward_A < max_capacity) & (patient_count_in_ward_B < max_capacity)
# TRUE & FALSE case
(patient_count_in_ward_A < max_capacity) & (patient_count_in_ward_E < max_capacity)
```

#### |

The `|` operator means logical OR which returns `TRUE` if at least one of the conditions is true.

```{webr}
#| envir: making_comparisons
#| label: logical OR
# TRUE & FALSE case
(patient_count_in_ward_A < max_capacity) | 
(patient_count_in_ward_E < max_capacity)
# FALSE & FALSE case
(patient_count_in_ward_A < patient_count_in_ward_B) | 
(patient_count_in_ward_A < patient_count_in_ward_D)
```

#### !

The `!` operator means logical NOT which returns `TRUE` if the condition is false.

```{webr}
#| envir: making_comparisons
#| label: logical NOT
# !(10 < 12)
!(patient_count_in_ward_A < max_capacity)
# !(20 < 12)
!(patient_count_in_ward_E < max_capacity)
```

#### is.na()

The `is.na` function returns TRUE if a value is `NA`.

```{webr}
#| envir: making_comparisons
#| label: is.na usage
x <- c(1, 2, NA, 4)
is.na(x)
```

#### isTRUE()

The `isTRUE` function returns TRUE for TRUE elements, FALSE for FALSE elements. Please note that this function only works in length one logical vectors. To apply this check element wise on a logical vector greater than 1, one work around is to use `Vectorize`.

```{webr}
#| envir: making_comparisons
#| label: isTRUE usage
isTRUE(TRUE)
isTRUE(FALSE)
isTRUE(NA)
# To check element wise
is_true <- Vectorize(isTRUE)
is_true(c(TRUE, FALSE, NA))
```

#### isFALSE()

The `isFALSE` function returns FALSE for TRUE elements, TRUE for FALSE elements.

```{webr}
#| envir: making_comparisons
#| label: isFALSE usage
isFALSE(TRUE)
isFALSE(FALSE)
isFALSE(NA)
# To check element wise
is_false <- Vectorize(isFALSE)
is_false(c(TRUE, FALSE, NA))
```

#### %in%

The `%in%` operator checks if a value or set of values on the left side is present in a vector or list on the right side.

```{webr}
#| envir: making_comparisons
#| label: in usage
c("😁", "🤣", "😎", "😀") %in% c("🫩", "😎", "😀", "🥰", "🤩", "🙂")
```

#### %notin%

The `%notin%` operator was introduced in R version 4.6.0. It checks if a value or set of values on the left side is absent in a vector or list on the right side.

```{webr}
#| envir: making_comparisons
#| label: notin usage
c("😁", "🤣", "😎", "😀") %notin% c("🫩", "😎", "😀", "🥰", "🤩", "🙂")
```

:::

<!-- <https://resbaz.github.io/2014-r-materials/lessons/01-intro_r/data-structures.html> -->